package com.chargebee.models.enums 
sealed trait EventType 
case object PLAN_CREATED extends EventType 
case object PLAN_UPDATED extends EventType 
case object PLAN_DELETED extends EventType 
case object ADDON_CREATED extends EventType 
case object ADDON_UPDATED extends EventType 
case object ADDON_DELETED extends EventType 
case object COUPON_CREATED extends EventType 
case object COUPON_UPDATED extends EventType 
case object COUPON_DELETED extends EventType 
case object COUPON_SET_CREATED extends EventType 
case object COUPON_SET_UPDATED extends EventType 
case object COUPON_SET_DELETED extends EventType 
case object COUPON_CODES_ADDED extends EventType 
case object COUPON_CODES_DELETED extends EventType 
case object COUPON_CODES_UPDATED extends EventType 
case object CUSTOMER_CREATED extends EventType 
case object CUSTOMER_CHANGED extends EventType 
case object CUSTOMER_DELETED extends EventType 
case object CUSTOMER_MOVED_OUT extends EventType 
case object CUSTOMER_MOVED_IN extends EventType 
case object PROMOTIONAL_CREDITS_ADDED extends EventType 
case object PROMOTIONAL_CREDITS_DEDUCTED extends EventType 
case object SUBSCRIPTION_CREATED extends EventType 
case object SUBSCRIPTION_STARTED extends EventType 
case object SUBSCRIPTION_TRIAL_END_REMINDER extends EventType 
case object SUBSCRIPTION_ACTIVATED extends EventType 
case object SUBSCRIPTION_CHANGED extends EventType 
case object SUBSCRIPTION_CANCELLATION_SCHEDULED extends EventType 
case object SUBSCRIPTION_CANCELLATION_REMINDER extends EventType 
case object SUBSCRIPTION_CANCELLED extends EventType 
case object SUBSCRIPTION_REACTIVATED extends EventType 
case object SUBSCRIPTION_RENEWED extends EventType 
case object SUBSCRIPTION_SCHEDULED_CANCELLATION_REMOVED extends EventType 
case object SUBSCRIPTION_CHANGES_SCHEDULED extends EventType 
case object SUBSCRIPTION_SCHEDULED_CHANGES_REMOVED extends EventType 
case object SUBSCRIPTION_SHIPPING_ADDRESS_UPDATED extends EventType 
case object SUBSCRIPTION_DELETED extends EventType 
case object SUBSCRIPTION_PAUSED extends EventType 
case object SUBSCRIPTION_PAUSE_SCHEDULED extends EventType 
case object SUBSCRIPTION_SCHEDULED_PAUSE_REMOVED extends EventType 
case object SUBSCRIPTION_RESUMED extends EventType 
case object SUBSCRIPTION_RESUMPTION_SCHEDULED extends EventType 
case object SUBSCRIPTION_SCHEDULED_RESUMPTION_REMOVED extends EventType 
case object PENDING_INVOICE_CREATED extends EventType 
case object PENDING_INVOICE_UPDATED extends EventType 
case object INVOICE_GENERATED extends EventType 
case object INVOICE_UPDATED extends EventType 
case object INVOICE_DELETED extends EventType 
case object CREDIT_NOTE_CREATED extends EventType 
case object CREDIT_NOTE_UPDATED extends EventType 
case object CREDIT_NOTE_DELETED extends EventType 
case object SUBSCRIPTION_RENEWAL_REMINDER extends EventType 
case object TRANSACTION_CREATED extends EventType 
case object TRANSACTION_UPDATED extends EventType 
case object TRANSACTION_DELETED extends EventType 
case object PAYMENT_SUCCEEDED extends EventType 
case object PAYMENT_FAILED extends EventType 
case object PAYMENT_REFUNDED extends EventType 
case object PAYMENT_INITIATED extends EventType 
case object REFUND_INITIATED extends EventType 
case object NETD_PAYMENT_DUE_REMINDER extends EventType 
case object AUTHORIZATION_SUCCEEDED extends EventType 
case object AUTHORIZATION_VOIDED extends EventType 
case object CARD_ADDED extends EventType 
case object CARD_UPDATED extends EventType 
case object CARD_EXPIRY_REMINDER extends EventType 
case object CARD_EXPIRED extends EventType 
case object CARD_DELETED extends EventType 
case object PAYMENT_SOURCE_ADDED extends EventType 
case object PAYMENT_SOURCE_UPDATED extends EventType 
case object PAYMENT_SOURCE_DELETED extends EventType 
case object VIRTUAL_BANK_ACCOUNT_ADDED extends EventType 
case object VIRTUAL_BANK_ACCOUNT_UPDATED extends EventType 
case object VIRTUAL_BANK_ACCOUNT_DELETED extends EventType 
case object TOKEN_CREATED extends EventType 
case object TOKEN_CONSUMED extends EventType 
case object TOKEN_EXPIRED extends EventType 
case object UNBILLED_CHARGES_CREATED extends EventType 
case object UNBILLED_CHARGES_VOIDED extends EventType 
case object UNBILLED_CHARGES_DELETED extends EventType 
case object UNBILLED_CHARGES_INVOICED extends EventType 
case object ORDER_CREATED extends EventType 
case object ORDER_UPDATED extends EventType 
case object ORDER_CANCELLED extends EventType 
case object ORDER_DELIVERED extends EventType 
case object ORDER_RETURNED extends EventType 
case object ORDER_READY_TO_PROCESS extends EventType 
case object ORDER_READY_TO_SHIP extends EventType 
case object QUOTE_CREATED extends EventType 
case object QUOTE_UPDATED extends EventType 
case object QUOTE_DELETED extends EventType 
case object GIFT_SCHEDULED extends EventType 
case object GIFT_UNCLAIMED extends EventType 
case object GIFT_CLAIMED extends EventType 
case object GIFT_EXPIRED extends EventType 
case object GIFT_CANCELLED extends EventType 
case object GIFT_UPDATED extends EventType 
case object HIERARCHY_CREATED extends EventType 
case object HIERARCHY_DELETED extends EventType 
case object PAYMENT_INTENT_CREATED extends EventType 
case object PAYMENT_INTENT_UPDATED extends EventType 
case object _UNKNOWN extends EventType 
