package com.chargebee.models.enums 
sealed trait Gateway 
case object CHARGEBEE extends Gateway 
case object STRIPE extends Gateway 
case object WEPAY extends Gateway 
case object BRAINTREE extends Gateway 
case object AUTHORIZE_NET extends Gateway 
case object PAYPAL_PRO extends Gateway 
case object PIN extends Gateway 
case object EWAY extends Gateway 
case object EWAY_RAPID extends Gateway 
case object WORLDPAY extends Gateway 
case object BALANCED_PAYMENTS extends Gateway 
case object BEANSTREAM extends Gateway 
case object BLUEPAY extends Gateway 
case object ELAVON extends Gateway 
case object FIRST_DATA_GLOBAL extends Gateway 
case object HDFC extends Gateway 
case object MIGS extends Gateway 
case object NMI extends Gateway 
case object OGONE extends Gateway 
case object PAYMILL extends Gateway 
case object PAYPAL_PAYFLOW_PRO extends Gateway 
case object SAGE_PAY extends Gateway 
case object TCO extends Gateway 
case object WIRECARD extends Gateway 
case object AMAZON_PAYMENTS extends Gateway 
case object PAYPAL_EXPRESS_CHECKOUT extends Gateway 
case object GOCARDLESS extends Gateway 
case object ADYEN extends Gateway 
case object ORBITAL extends Gateway 
case object MONERIS_US extends Gateway 
case object MONERIS extends Gateway 
case object BLUESNAP extends Gateway 
case object CYBERSOURCE extends Gateway 
case object VANTIV extends Gateway 
case object NOT_APPLICABLE extends Gateway 
case object _UNKNOWN extends Gateway 
